name: Daily Bonus
 
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 15 * * *' # 北京时间 23:00 自动运行
  workflow_dispatch:      # 允许你在网页上手动点按钮测试

jobs:
  checkin:
    strategy:
      matrix:
        os: [self-hosted]
        # os: [ubuntu-latest, self-hosted]

    runs-on: ${{ matrix.os }}

    env:
      V2EX_COOKIES: ${{ secrets.V2EX_COOKIES }}
      BILIBILI_COOKIES: ${{ secrets.BILIBILI_COOKIES }}
      YAMIBO_COOKIES: ${{ secrets.YAMIBO_COOKIES }}
      YURIFANS_EMAIL: ${{ secrets.YURIFANS_EMAIL }}
      YURIFANS_PASSWORD: ${{ secrets.YURIFANS_PASSWORD }}
      PICA_EMAIL: ${{ secrets.PICA_EMAIL }}
      PICA_PASSWORD: ${{ secrets.PICA_PASSWORD }}
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      TG_USER_ID: ${{ secrets.TG_USER_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
  
      - name: Check-in
        run: |
          # 1. 之前补齐 3.13 缺失组件的命令（保留以防万一，但只需跑一次）
          python -c "import os; lib_path=os.path.join(os.path.dirname(os.__file__), 'imghdr.py'); not os.path.exists(lib_path) and open(lib_path, 'w').write('def what(file, h=None): return None')"
          
          # 2. 运行签到脚本（因为依赖已经在手机里装好了，直接跑就行）
          python ./message.py
